[package]
name = "dumbmem"
version = "0.1.0"
description = "A dumb tool to collect dumb memory consumption numbers over time"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.4.14", features = ["cargo", "derive", "env"] }
ctrlc = "3.4.4"
shellwords = "1.1.0"
